require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.neovim-ayu")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.presence")
require("core.plugin_config.nightfox")
require("core.plugin_config.lsp_config")
